import { Inter } from "next/font/google";
import "./globals.css";
import { AuthUserProvider } from "@/firebase/auth";
import { Suspense } from "react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "To-Do App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthUserProvider><Suspense fallback>{children}</Suspense></AuthUserProvider>
      </body>
    </html>
  );
}
